spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8083/
          predicates:
            - Path = /students/**
        - id: r2
          uri: http://localhost:8084/
          predicates:
            - Path = /professors/**
        - id: r3
          uri: http://localhost:8081/
          predicates:
            - Path = /courses/**