spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://STUDENTS-SERVICE
          predicates:
            - Path= /students/**
        - id: r2
          uri: lb://PROFESSORS-SERVICE
          predicates:
            - Path= /professors/**
        - id: r3
          uri: lb://COURSES-SERVICE
          predicates:
            - Path= /courses/**